class Token:
    inner: str

    def __init__(self, inner: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class JapaneseNERProcessor:
    def __init__(self) -> None: ...
    def recognize(self, text: str) -> list[Token]: ...
